---
# tasks file for network_backup

- name: backup running-config to local directory
  cisco.ios.ios_config:
    backup: true
    backup_options:
      filename: "{{ inventory_hostname }}_{{ time_output.stdout }}.txt"
      dir_path: "{{ git_dest }}{{ time_output.stdout }}"
  notify: push to git
